name: Simple CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate HTML
        uses: anra0/linter-html-validator@v1
        with:
          path: ./*.html

      - name: No new changes
        run: echo "No new changes to deploy."
